build:
	gcc -o sudoku -Wall sudoku_serial.c
clean:
	rm -f sudoku
run_easy:
	./sudoku sudoku_easy_1.in
	./sudoku sudoku_easy_2.in
run_medium:
	./sudoku sudoku_medium_1.in
run_hard:
	./sudoku sudoku_hard_1.in
run_impossible:
	./sudoku sudoku_impossible_1.in
